### ISSUE TITLE
Particle area doesn't resize on page size change

### ISSUE THREAD

**Issue by colinricardo** [transitive-bullshit/react-particle-animation#1]
## Issue
If you load the page while browser is at e.g. half width, then resize the page, the particles only cover the initial size of the page.

## Screenshot
![image](https://user-images.githubusercontent.com/21294951/39531800-f21177ec-4e23-11e8-8633-95faba420b87.png)

**Comment by transitive-bullshit** [comment]
This should be fixed in `v1.0.1`.

Thanks!
