### ISSUE TITLE
Change property of particles on fly

### ISSUE THREAD

**Issue by 07pepa** [transitive-bullshit/react-particle-animation#2]
I would like to change property of particles on the fly... Is there way to do it(hack it)...

**Comment by transitive-bullshit** [comment]
It's definitely possible with some slight changes to the source.  Which props do you want to make dynamic?

**Comment by 07pepa** [comment]
well size and color(more is "better").... but...  it will be probably often called function(or often changed value) (up to one every 1/60th of second) ... so optimalisation  is priority...

**Comment by transitive-bullshit** [comment]
I just published `v1.0.1` which makes all props dynamic. The simulation will no longer reset itself whenever you change a prop, but rather update itself as minimally as possible to accommodate the changes.
